version: '3'
services:
  mongodb:
    container_name: mongodb
    image: mongo:5.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - $PWD/infra/data/mongo:/data/db
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3001:3000"
    depends_on:
      - mongodb